New dev sprint5
ClevertecFrontendLab/sidorov-dv pull request #3
Opened 2023-03-09 12:35 UTC by sidorov-dv

2023-03-09 13:33 UTC, Ivan6813 requested changes

2023-03-09 13:33 UTC, Ivan6813 commented on src/components/sign-up/fail-data-register.jsx
> +);
одна из фишек React это возможность переиспользовать компоненты. У тебя компоненты fail-screen, fail-save-pass и  fail-data-register одинаковые, почему бы не сделать универсальный компонент и данные прокидывать пропсами

2023-03-09 13:33 UTC, Ivan6813 commented on src/components/sign-up/not-save-data-register.jsx
> +    </div>
идентичный кусок кода как и в файлах fail-screen, fail-save-pass и fail-data-register. Когда сделаешь универсальный компонент для fail-screen, fail-save-pass и fail-data-register, то можно будет и здесь его использовать

2023-03-09 13:33 UTC, Ivan6813 commented on src/components/sign-up/sign-up.jsx
> +                        <span className={classes.word__error} style={{ color: '#a7a7a7' }}>
может есть возможность отказаться от использования здесь инлайновых стилей? ты же и так класс добавил

2023-03-09 13:33 UTC, Ivan6813 commented on src/components/sign-up/sign-up.jsx
> +            </div>
пересмотри код на возможность переиспользования кода, у тебя хватает мест, где можно сделать универсальный компонент и переиспользовать его. И тогда твои компоненты не будут раздуты на 350 строк. В step 2 у тебя два идентичных куска кода

2023-03-09 13:33 UTC, Ivan6813 commented on src/components/sign-up/sign-up.jsx
> +                    value: /^[-.\w]+@([\w-]+\.)+[\w-]+$/,
регулярные выражения лучше выносить в константы и давать этой константе понятное название - это улучшит читаемость твоего кода

2023-03-09 13:33 UTC, Ivan6813 commented on src/components/sign-up/success-register.jsx
> +    </div>
тоже одинаковый кусок кода как и в fail-screen, fail-save-pass и fail-data-register)

2023-03-09 13:33 UTC, Ivan6813 commented on src/pages/registration/registration-page.jsx
> +    </div>
одинаковый код как и в authorization-page и в password-page

2023-03-10 09:32 UTC, sidorov-dv commented
Все замечания поправил

2023-03-10 09:38 UTC, Ivan6813 approved these changes

2023-03-10 09:53 UTC, merged